//using System;
//class Calc
//{
//    public void printDivide(int x, int y)
//    {
//        int z;
//        try
//        {
//            z = x / y;
//            Console.WriteLine(z);
//        }
//        catch (Exception e)
//        {
//            Console.WriteLine("printDivide()で例外発生！");
//            Console.WriteLine(e.Message);
//        }
//    }
//}

//class ExceptionSample
//{
//    static void Main()
//    {
//        Calc calc = new Calc();
//        calc.printDivide(30, 0);
//        Console.WriteLine("終了しました。");
//    }
//}